lampShade/ServiceHost/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            return View();
        }

    }
}

lampShade/ServiceHost/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            return View();
        }

    }
}

lampShade/ServiceHost/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lampshade Store</title>

    <!-- Vendor CSS -->
    <link href="~/Theme/assets/css/vendors.css" rel="stylesheet">
    <!-- Main CSS -->
    <link href="~/Theme/assets/css/style.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Theme/assets/css/Custom.css" rel="stylesheet">
</head>

<body>

@await Component.InvokeAsync("Menu")


@RenderBody()

@await Component.InvokeAsync("Footer")


<div class="search-overlay" id="search-overlay">
        <a href="javascript:void(0)" class="close-search-overlay" id="close-search-overlay">
            <i class="ion-ios-close-empty"></i>
        </a>


        <div class="search-form">
            <form method="get" asp-page="/Search">
                <input type="search" name="value" id="value" placeholder="Search entire store here ...">
                <button type="submit">
                    <i class="ion-android-search"></i>
                </button>
            </form>
        </div>

    </div>


    <div id="scroll-top">
        <span>بروبالا</span><i class="ion-chevron-right"></i><i class="ion-chevron-right"></i>
    </div>

<script src="~/Theme/assets/js/vendors.js"></script>

    <script src="~/Theme/assets/js/active.js"></script>

</body>

</html>